config/routes.rb
Rails.application.routes.draw do
  get 'contact_info/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   get 'sessions/new'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   root 'users#home'


   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout',  to: 'sessions#destroy'
   get '/logout',  to: 'sessions#destroy'
   get  '/update',  to: 'users#edit'
   patch '/update',  to: 'users#update'
   get '/search', to: 'search#index'
   get 'search/results' => 'search#show'
   get '/index', to: 'users#index'
   get '/contact', to: 'contact_info#show'

   resources :users
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :account_activations, only: [:edit]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Savage Six</title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand">
      <%= image_tag("logo.jpg", height: '40', width: '40', class: "d-inline-block align-top", id: "navbar-logo") %>
      <%= link_to 'Savage Six Site', root_path %>
    </a>
    <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
      <ul class="navbar-nav">
        <% if is_admin? %>
          <li class="navbar-nav">
            <a class="navbar-link" <%= link_to "Admin", rails_admin_path %>
          </li>
        <% end %>
        <li class="navbar-nav">
          <a class="nav-link" <%= link_to "Home", root_path %> </a>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Search a cadet", index_path %> </a>
            <button type="button" class="btn btn-md"> <%= link_to "Sign out", logout_path, method: :delete %> </button>
          </li>
        <% else %>
          <li class="nav-item">
            <button type="button" class="btn btn-md"> <%= link_to 'Sign In', login_path %></button>
          </li>
        <% end %>

        <li class="nav-item">
          <% if logged_in? %>
            <a class="nav-link" <%= link_to "Profile", current_user %> </a>
          <% else %>
            <button type="button" class="btn btn-md"> <%= link_to 'Sign Up', new_user_path %> </button>
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to 'Contact us', contact_path %> </a>
        </li>
      </ul>
    </div>
  </nav>
</head>
<body>
<% if flash[:alert] %>
  <div class="alert alert-warning"><%= simple_format(flash[:alert]) %></div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>

<div class="container">
  <%= yield %>
</div>
</body>
</html>